# Generated by Django 6.0.2 on 2026-02-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=120, verbose_name='место привычки')),
                ('time_moment', models.TimeField(verbose_name='время привычки')),
                ('action', models.TextField(verbose_name='действие привычки')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodicity', models.TextField(verbose_name='периодичность привычки')),
                ('reward', models.TextField(verbose_name='вознаграждение')),
                ('duration', models.TimeField(verbose_name='время на выполнение привычки')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичность')),
                ('linked_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='свяазанная привычка')),
            ],
        ),
    ]
