# Generated by Django 6.0.2 on 2026-02-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='linked_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='свяазанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.TextField(default='ежедневная', verbose_name='периодичность привычки'),
        ),
    ]
