# Generated by Django 6.0.2 on 2026-02-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_linked_habit_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='linked_habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='свяазанная привычка'),
        ),
    ]
